src/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('books/', views.BookListView.as_view(), name='book-list'),
    path('books/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('books/<int:pk>/update/',
         views.BookUpdateView.as_view(), name='book-update'),
    path('books/<int:pk>/delete/',
         views.BookDeleteView.as_view(), name='book-delete'),
    path('loans/', views.LoanListView.as_view(), name='loan-list'),
    path('loans/<int:pk>/', views.LoanDetailView.as_view(), name='loan-detail'),
    path('loans/<int:book_id>/create/',
         views.LoanCreateView.as_view(), name='loan-create'),
    path('loans/<int:pk>/update/',
         views.LoanUpdateView.as_view(), name='loan-update'),
    path('loans/<int:pk>/delete/',
         views.LoanDeleteView.as_view(), name='loan-delete'),
    path('import-books/', views.ImportBooksView.as_view(), name='import-books'),

]

src/library_web_apps/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('auth/', include('users.urls')),
]

src/core/models.py
from django.db import models
from users.models import User
from django.utils import timezone


class Book(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    number = models.IntegerField(unique=True, primary_key=True)
    title = models.CharField(max_length=255)
    release_date = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    description = models.TextField()
    pages = models.IntegerField()
    cover = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Loan(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    borrow_date = models.DateField(default=timezone.now)
    return_date = models.DateField()

    def __str__(self):
        return f'{self.user} - {self.book}'

src/templates/dashboard/base.html
{% extends "base.html" %}
{% block title %}
  Dashboard
{% endblock title %}
{% block content %}
{% endblock content %}

src/templates/dashboard/dashboard.html
{% extends "dashboard/base.html" %}
{% block content %}
  <h1>Dashboard - {{ request.user }}</h1>
  {% if request.user.is_staff %}
    <div class="text-center mt-4">
      <a href="{% url 'core:import-books' %}" class="btn btn-success">Impor Buku</a>
    </div>
    <h2 class="mt-5">Daftar Peminjaman</h2>
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Buku</th>
          <th>Peminjam</th>
          <th>Email</th>
          <th>Tanggal Pinjam</th>
          <th>Tanggal Kembali</th>
        </tr>
      </thead>
      <tbody>
        {% for loan in loans %}
          <tr>
            <td>{{ loan.id }}</td>
            <td>{{ loan.book.title }}</td>
            <td>{{ loan.user.name }}</td>
            <td>{{ loan.user.email }}</td>
            <td>{{ loan.borrow_date }}</td>
            <td>{{ loan.return_date }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="5" class="text-center">Tidak ada Peminjaman saat ini.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    {% include "core/loan_list.html" with loans=loans %}
  {% endif %}
{% endblock content %}

src/templates/dashboard/sidebar.html
{% load static %}
<div class="sidebar d-flex flex-column p-3 bg-primary"
     style="height: 100vh;
            position: fixed;
            top: 0;
            left: 0;
            z-index: 1000">
  <h4 class="text-white mb-4">Menu</h4>
  <a href="{% url 'core:book-list' %}" class="text-white mb-2">Buku</a>
  <a href="{% url 'core:loan-list' %}" class="text-white mb-2">Pinjam</a>
</div>