src/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('books/', views.BookListView.as_view(), name='book-list'),
    path('books/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('books/<int:pk>/update/',
         views.BookUpdateView.as_view(), name='book-update'),
    path('books/<int:pk>/delete/',
         views.BookDeleteView.as_view(), name='book-delete'),
    path('loans/', views.LoanListView.as_view(), name='loan-list'),
    path('loans/<int:pk>/', views.LoanDetailView.as_view(), name='loan-detail'),
    path('loans/<int:book_id>/create/',
         views.LoanCreateView.as_view(), name='loan-create'),
    path('loans/<int:pk>/update/',
         views.LoanUpdateView.as_view(), name='loan-update'),
    path('loans/<int:pk>/delete/',
         views.LoanDeleteView.as_view(), name='loan-delete'),
    path('import-books/', views.ImportBooksView.as_view(), name='import-books'),

]

src/library_web_apps/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('auth/', include('users.urls')),
]

src/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.UserCreateView.as_view(), name='signup'),
    path('admin/signup/', views.admin_signup, name='admin_signup'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('users/<int:pk>/update/',
         views.UserUpdateView.as_view(), name='user_update'),
    path('users/<int:pk>/delete/',
         views.UserDeleteView.as_view(), name='user_delete'),
]

src/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %}
      {% endblock title %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdn.jsdelivr.net/npm/mdb-ui-kit@8.0.0/css/mdb.min.css"
          rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'index.css' %}">
  </head>
  <body>
    <div id="container">
      {% include "nav.html" %}
      {% block outercontent %}
      {% endblock outercontent %}
      <div class="p-3" id="content">
        {% for message in messages %}<div class="alert alert-{{ message.tags }}">{{ message }}</div>{% endfor %}
        {% block content %}
        {% endblock content %}
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
            integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
            crossorigin="anonymous"></script>
    <!-- MDB -->
    <script type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/mdb-ui-kit@8.0.0/js/mdb.umd.min.js"></script>
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}
{% block title %}
  Home Page
{% endblock title %}
{% block outercontent %}
  <header class="position-relative overflow-hidden">
    <div class="bg-image">
      <picture>
        <source media="(max-width: 768px)"
                srcset="https://images.pexels.com/photos/8199251/pexels-photo-8199251.jpeg">
        <source media="(min-width: 769px)"
                srcset="https://images.pexels.com/photos/8199562/pexels-photo-8199562.jpeg">
        <img src="https://images.pexels.com/photos/8199562/pexels-photo-8199562.jpeg"
             class="img-fluid w-100"
             style="object-fit: cover;
                    height: 100vh;
                    width: 100%"
             alt="Library Image">
      </picture>
      <div class="p-3 d-flex align-items-center flex-column justify-content-center text-center mask"
           style="background-color: hsla(0, 0%, 0%, 0.6)">
        <h1 class="mb-3 text-primary">Welcome to the Perpustakaan Online</h1>
        <h4 class="mb-3 text-primary">Read, Learn, and Grow</h4>
        <button type="button"
                class="btn btn-primary btn-lg"
                data-mdb-ripple-init
                data-mdb-ripple-color="light"
                onclick="location.href='{% url 'core:book-list' %}'">Lihat Buku</button>
      </div>
    </div>
  </header>
{% endblock outercontent %}

src/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button for small screens -->
    <button data-mdb-collapse-init
            class="navbar-toggler"
            type="button"
            data-mdb-target="#navbarCenteredExample"
            aria-controls="navbarCenteredExample"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <i class="fas fa-bars text-white"></i>
    </button>
    <!-- Brand/logo -->
    <a class="navbar-brand" href="{% url 'core:home' %}">
      <div class="d-flex align-items-center p-2">
        <div class="me-2">
          <i class="fas fa-book text-white"></i>
        </div>
        <div>
          <h3 class="m-0 text-white">Perpustakaan Online</h3>
        </div>
      </div>
    </a>
    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse d-flex justify-content-end"
         id="navbarCenteredExample">
      <!-- Navigation links -->
      <ul class="navbar-nav mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link text-white {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}"
               href="{% url 'core:dashboard' %}">Dashboard</a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link text-white {% if request.resolver_match.url_name == 'book-list' %}active{% endif %}"
             href="{% url 'core:book-list' %}">Buku</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'users:logout' %}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link text-white {% if request.resolver_match.url_name == 'login' %}active{% endif %}"
               href="{% url 'users:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white {% if request.resolver_match.url_name == 'signup' %}active{% endif %}"
               href="{% url 'users:signup' %}">Daftar</a>
          </li>
        {% endif %}
      </ul>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>