src/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('books/', views.BookListView.as_view(), name='book-list'),
    path('books/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('books/<int:pk>/update/',
         views.BookUpdateView.as_view(), name='book-update'),
    path('books/<int:pk>/delete/',
         views.BookDeleteView.as_view(), name='book-delete'),
    path('loans/', views.LoanListView.as_view(), name='loan-list'),
    path('loans/<int:pk>/', views.LoanDetailView.as_view(), name='loan-detail'),
    path('loans/<int:book_id>/create/',
         views.LoanCreateView.as_view(), name='loan-create'),
    path('loans/<int:pk>/update/',
         views.LoanUpdateView.as_view(), name='loan-update'),
    path('loans/<int:pk>/delete/',
         views.LoanDeleteView.as_view(), name='loan-delete'),
    path('import-books/', views.ImportBooksView.as_view(), name='import-books'),

]

src/library_web_apps/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('auth/', include('users.urls')),
]

src/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.UserCreateView.as_view(), name='signup'),
    path('admin/signup/', views.admin_signup, name='admin_signup'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('users/<int:pk>/update/',
         views.UserUpdateView.as_view(), name='user_update'),
    path('users/<int:pk>/delete/',
         views.UserDeleteView.as_view(), name='user_delete'),
]

src/core/models.py
from django.db import models
from users.models import User
from django.utils import timezone


class Book(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    number = models.IntegerField(unique=True, primary_key=True)
    title = models.CharField(max_length=255)
    release_date = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    description = models.TextField()
    pages = models.IntegerField()
    cover = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Loan(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    borrow_date = models.DateField(default=timezone.now)
    return_date = models.DateField()

    def __str__(self):
        return f'{self.user} - {self.book}'

src/core/forms.py
from django import forms

from .models import Book, Loan


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('number', 'title', 'release_date',
                  'author', 'description', 'pages', 'cover')


class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ('book', 'user', 'borrow_date', 'return_date')

src/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.views import View
from django.utils import timezone
from datetime import timedelta
import requests
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Book, Loan
from .forms import BookForm, LoanForm


class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


class HomeView(TemplateView):
    template_name = 'home.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('core:dashboard')
        return super().get(request, *args, **kwargs)


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        if user.is_staff:
            context['is_admin'] = True
            loan = Loan.objects.all()
            context['loans'] = loan
        else:
            loans = Loan.objects.filter(user=user)
            context['loans'] = loans

        return context


class BookListView(ListView):
    template_name = 'core/book_list.html'
    context_object_name = 'books'

    def get_queryset(self):
        return Book.objects.all()


class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book'


class BookCreateView(StaffRequiredMixin, CreateView):
    model = Book
    form_class = BookForm
    success_url = '/books'


class BookUpdateView(StaffRequiredMixin, UpdateView):
    model = Book
    form_class = BookForm
    success_url = '/books'


class BookDeleteView(StaffRequiredMixin, DeleteView):
    model = Book
    success_url = '/books'


class LoanListView(LoginRequiredMixin, ListView):
    model = Loan
    context_object_name = 'dashboard'

    def get_queryset(self):
        return Loan.objects.filter(user=self.request.user)


class LoanDetailView(LoginRequiredMixin, DetailView):
    model = Loan
    context_object_name = 'loan'

    def get_queryset(self):
        return Loan.objects.filter(user=self.request.user)


class LoanCreateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        book_id = kwargs.get('book_id')
        book = get_object_or_404(Book, number=book_id)
        existing_loan = Loan.objects.filter(user=request.user).first()

        if existing_loan:
            messages.warning(request,
                             (f'Kamu sedang meminjam buku {existing_loan.book.title}.'
                              f'\n Kamu harus mengembalikan buku itu sebelum meminjam buku baru.'))
            return redirect('core:dashboard')

        borrow_date = timezone.now().date()
        return_date = borrow_date + timedelta(days=14)

        Loan.objects.create(user=request.user, book=book,
                            borrow_date=borrow_date, return_date=return_date)

        messages.success(
            request, f"Kamu berhasil meminjam buku '{book.title}'.")
        return redirect('core:dashboard')


class LoanUpdateView(LoginRequiredMixin, UpdateView):
    model = Loan
    form_class = LoanForm
    success_url = '/dashboard'

    def get_queryset(self):
        return Loan.objects.filter(user=self.request.user)


class LoanDeleteView(LoginRequiredMixin, DeleteView):
    model = Loan
    success_url = '/dashboard'

    def get_queryset(self):
        return Loan.objects.filter(user=self.request.user)


class ImportBooksView(StaffRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        books = self.get_books_from_api()
        count = 0
        for book_data in books:
            book, created = Book.objects.get_or_create(
                number=book_data.get('number'),
                title=book_data.get('title'),
                release_date=book_data.get('releaseDate'),
                description=book_data.get('description'),
                pages=book_data.get('pages'),
                cover=book_data.get('cover')
            )
            if created:
                count += 1
        messages.success(request, f'{count} buku berhasil di-import.')
        return redirect('core:dashboard')

    def get_books_from_api(self):
        try:
            response = requests.get(
                'https://potterapi-fedeperin.vercel.app/en/books')
            response.raise_for_status()
            return response.json()
        except requests.RequestException as e:
            messages.error(self.request, f"Error fetching books: {e}")
            return []

src/templates/core/book_confirm_delete.html
{% extends "base.html" %}
{% block title %}
  Confirm Deletion
{% endblock title %}
{% block content %}
  <div class="container">
    <h1>Apakah Anda yakin ingin menghapus buku "{{ book.title }}"?</h1>
    <p>Data yang dihapus tidak dapat dikembalikan.</p>
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Hapus</button>
      <a href="{% url 'core:book-list' %}" class="btn btn-secondary">Batal</a>
    </form>
  </div>
{% endblock %}

src/templates/core/book_list.html
{% extends "base.html" %}
{% block title %}
  Daftar Buku
{% endblock title %}
{% block content %}
  <h1 class="text-center">Daftar Buku</h1>
  <div class="container">
    <div class="row justify-content-center">
      {% if books %}
        {% for book in books %}
          <div class="col-md-8 mb-4">
            <div class="book-item card">
              <div class="card-body d-flex flex-column align-items-center">
                <h2 class="card-title">{{ book.number }}. {{ book.title }}</h2>
                <p>
                  <strong>Release Date:</strong> {{ book.release_date }}
                </p>
                <p>
                  <strong>Description:</strong> {{ book.description }}
                </p>
                <p>
                  <strong>Pages:</strong> {{ book.pages }}
                </p>
                <div class="d-flex justify-content-center mb-3">
                  <img src="{{ book.cover }}"
                       alt="Cover of {{ book.title }}"
                       class="img-fluid"
                       style="max-width: 100%;
                              height: auto">
                </div>
                {% if user.is_authenticated and not user.is_staff %}
                  <div class="w-50 my-3">
                    <a href="{% url 'core:loan-create' book.number %}"
                       class="btn btn-primary btn-block">Pinjam</a>
                  </div>
                {% elif user.is_staff %}
                  <div class="w-50 my-3">
                    <a href="{% url 'core:book-delete' book.number %}"
                       class="btn btn-danger btn-block">Hapus</a>
                  </div>
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      {% else %}
        {% if user.is_authenticated and not user.is_staff %}
          <div class="text-center my-4">
            <p>
              Belum ada buku. Untuk menambahkan buku, silakan <a href="{% url 'users:admin_signup' %}">login sebagai admin</a>.
            </p>
          </div>
        {% else %}
          <div class="text-center mt-4">
            <a href="{% url 'core:import-books' %}" class="btn btn-success">Impor Buku</a>
          </div>
        {% endif %}
      {% endif %}
    </div>
  </div>
{% endblock content %}

src/templates/core/loan_confirm_delete.html
{% extends "base.html" %}
{% block title %}
  Konfirmasi Pengembalian Buku
{% endblock title %}
{% block content %}
  <div class="container mt-5">
    <h1 class="text-center">Konfirmasi Pengembalian</h1>
    <p>Apakah Anda yakin ingin mengembalikan "{{ loan.book.title }}"?</p>
    <form method="post" class="mt-4">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Ya</button>
      <a href="{% url 'core:dashboard' %}" class="btn btn-secondary">Batal</a>
    </form>
  </div>
{% endblock %}

src/templates/core/loan_list.html
{% block content %}
  <div class="container mt-5">
    <h1 class="text-center mb-4">Daftar Peminjaman</h1>
    <table class="table table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Buku</th>
          <th scope="col">Tanggal Pinjam</th>
          <th scope="col">Tanggal Kembali</th>
          <th scope="col">Status</th>
          <th scope="col">Aksi</th>
        </tr>
      </thead>
      <tbody>
        {% if loans %}
          {% for loan in loans %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ loan.book.title }}</td>
              <td>{{ loan.borrow_date|date:"d M Y" }}</td>
              <td>{{ loan.return_date|date:"d M Y" }}</td>
              <td>
                <span class="badge bg-warning text-dark">Belum Dikembalikan</span>
              </td>
              <td>
                <a href="{% url 'core:loan-delete' loan.pk %}"
                   class="btn btn-sm btn-danger">Kembalikan</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endif %}
    {% if loans %}
      <div class="text-center mt-4">
        <p class="text-danger">Anda sudah meminjam satu buku. Kembalikan buku tersebut sebelum meminjam yang lain.</p>
      </div>
    {% else %}
      <div class="text-center mt-4">
        <a href="{% url 'core:book-list' %}" class="btn btn-success">Tambah Peminjaman Baru</a>
      </div>
    {% endif %}
  </div>
{% endblock content %}